### ISSUE TITLE
advanced sessions incompatibility?

### ISSUE THREAD

**Issue by chozabu** [SRombauts/UE4GitPlugin#130]
Posted in the advanced forums thread here: https://forums.unrealengine.com/community/community-content-tools-and-tutorials/41043-advanced-sessions-plugin?p=1757704#post1757704

When trying to use this plugin (4.25) and advanced sessions I get an error when trying to package:

`PackagingResults: Error: System.ArgumentException: An item with the same key has already been added`

full error:

`
UATHelper: Packaging (Windows (64-bit)): ERROR: System.ArgumentException: An item with the same key has already been added.
UATHelper: Packaging (Windows (64-bit)):           at System.ThrowHelper.ThrowArgumentException(ExceptionResource resource)
UATHelper: Packaging (Windows (64-bit)):           at System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)
UATHelper: Packaging (Windows (64-bit)):           at System.Linq.Enumerable.ToDictionary[TSource,TKey,TElement](IEnumerable`1 source, Func`2 keySelector, Func`2 elementSelector, IEqualityComparer`1 comparer)
UATHelper: Packaging (Windows (64-bit)):           at AutomationTool.ProjectUtils.RequiresTempTarget(FileReference RawProjectPath, Boolean bProjectHasCode, UnrealTargetPlatform Platform, UnrealTargetConfiguration Configuration, TargetType TargetType, Boolean bRequiresAssetNativization, Boolean bRequiresCookedData, String& OutReason) in D:\Build\++UE4+License
e\Sync\Engine\Saved\CsTools\Engine\Source\Programs\AutomationTool\AutomationUtils\ProjectUtils.cs:line 208
UATHelper: Packaging (Windows (64-bit)):           at AutomationTool.ProjectUtils.RequiresTempTarget(FileReference RawProjectPath, List`1 Platforms, List`1 Configurations, Boolean AssetNativizationRequested) in D:\Build\++UE4+Licensee\Sync\Engine\Saved\CsTools\Engine\Source\Programs\AutomationTool\AutomationUtils\ProjectUtils.cs:line 155
UATHelper: Packaging (Windows (64-bit)):           at AutomationTool.ProjectUtils.DetectProjectProperties(FileReference RawProjectPath, List`1 ClientTargetPlatforms, List`1 ClientTargetConfigurations, Boolean AssetNativizationRequested) in D:\Build\++UE4+Licensee\Sync\Engine\Saved\CsTools\Engine\Source\Programs\AutomationTool\AutomationUtils\ProjectUtils.cs:
line 533
UATHelper: Packaging (Windows (64-bit)):           at AutomationTool.ProjectUtils.GetProjectProperties(FileReference RawProjectPath, List`1 ClientTargetPlatforms, List`1 ClientTargetConfigurations, Boolean AssetNativizationRequested) in D:\Build\++UE4+Licensee\Sync\Engine\Saved\CsTools\Engine\Source\Programs\AutomationTool\AutomationUtils\ProjectUtils.cs:lin
e 99
UATHelper: Packaging (Windows (64-bit)):           at AutomationTool.ProjectParams.AutodetectSettings(Boolean bReset) in D:\Build\++UE4+Licensee\Sync\Engine\Saved\CsTools\Engine\Source\Programs\AutomationTool\AutomationUtils\ProjectParams.cs:line 2010
UATHelper: Packaging (Windows (64-bit)):           at AutomationTool.ProjectParams..ctor(FileReference RawProjectPath, BuildCommand Command, String Device, String MapToRun, String AdditionalServerMapParams, ParamList`1 Port, String RunCommandline, String StageCommandline, String BundleName, String StageDirectoryParam, String UE4Exe, String SignPak, List`1 Cl
ientConfigsToBuild, List`1 ServerConfigsToBuild, ParamList`1 MapsToCook, ParamList`1 MapIniSectionsToCook, ParamList`1 DirectoriesToCook, String InternationalizationPreset, ParamList`1 CulturesToCook, ParamList`1 ClientCookedTargets, ParamList`1 EditorTargets, ParamList`1 ServerCookedTargets, List`1 ClientTargetPlatforms, Dictionary`2 ClientDependentPlatform
Map, List`1 ServerTargetPlatforms, Dictionary`2 ServerDependentPlatformMap, Nullable`1 Build, Nullable`1 SkipBuildClient, Nullable`1 SkipBuildEditor, Nullable`1 Cook, Nullable`1 Run, Nullable`1 SkipServer, Nullable`1 Clean, Nullable`1 Compressed, String AdditionalPakOptions, Nullable`1 IterativeCooking, String IterateSharedCookedBuild, Nullable`1 IterateShar
edBuildUsePrecompiledExe, Nullable`1 CookAll, Nullable`1 CookPartialGC, Nullable`1 CookInEditor, String CookOutputDir, Nullable`1 CookMapsOnly, Nullable`1 CookOnTheFly, Nullable`1 CookOnTheFlyStreaming, Nullable`1 UnversionedCookedContent, Nullable`1 EncryptIniFiles, Nullable`1 EncryptPakIndex, Nullable`1 EncryptEverything, Nullable`1 SkipCookingEditorConten
t, Nullable`1 NumCookersToSpawn, String AdditionalCookerOptions, String BasedOnReleaseVersion, String CreateReleaseVersion, String CreateReleaseVersionBasePath, String BasedOnReleaseVersionBasePath, Nullable`1 GeneratePatch, Nullable`1 AddPatchLevel, Nullable`1 StageBaseReleasePaks, Nullable`1 GenerateRemaster, String DiscVersion, String DLCName, String Diff
CookedContentPath, Nullable`1 DLCIncludeEngineContent, Nullable`1 DLCPakPluginFile, Nullable`1 DLCActLikePatch, Nullable`1 CrashReporter, Nullable`1 DedicatedServer, Nullable`1 Client, Nullable`1 Deploy, String DeployFolder, String GetFile, Nullable`1 FileServer, Nullable`1 Foreign, Nullable`1 ForeignCode, Nullable`1 LogWindow, Nullable`1 NoCleanStage, Nulla
ble`1 NoClient, Nullable`1 NoDebugInfo, Nullable`1 SeparateDebugInfo, Nullable`1 MapFile, Nullable`1 NoXGE, Nullable`1 Package, Nullable`1 Pak, Nullable`1 IoStore, Nullable`1 SkipIoStore, Nullable`1 Prereqs, String AppLocalDirectory, Nullable`1 NoBootstrapExe, Nullable`1 SignedPak, Nullable`1 PakAlignForMemoryMapping, Nullable`1 NullRHI, Nullable`1 FakeClien
t, Nullable`1 EditorTest, Nullable`1 RunAutomationTests, String RunAutomationTest, Nullable`1 CrashIndex, Nullable`1 SkipCook, Nullable`1 SkipCookOnTheFly, Nullable`1 SkipPak, Nullable`1 PrePak, Nullable`1 SkipStage, Nullable`1 Stage, Nullable`1 Manifests, Nullable`1 CreateChunkInstall, Nullable`1 Unattended, Nullable`1 NumClients, Nullable`1 Archive, String
 ArchiveDirectoryParam, Nullable`1 ArchiveMetaData, Nullable`1 CreateAppBundle, String SpecifiedClientTarget, String SpecifiedServerTarget, ParamList`1 ProgramTargets, Nullable`1 Distribution, Nullable`1 Prebuilt, Nullable`1 RunTimeoutSeconds, String SpecifiedArchitecture, String UbtArgs, String AdditionalPackageOptions, Nullable`1 IterativeDeploy, Nullable`
1 FastCook, Nullable`1 IgnoreCookErrors, Nullable`1 RunAssetNativization, Nullable`1 CodeSign, Nullable`1 TreatNonShippingBinariesAsDebugFiles, Nullable`1 UseExtraFlavor, String Provision, String Certificate, String Team, Boolean AutomaticSigning, ParamList`1 InMapsToRebuildLightMaps, ParamList`1 InMapsToRebuildHLOD, ParamList`1 TitleID) in D:\Build\++UE4+Li
censee\Sync\Engine\Saved\CsTools\Engine\Source\Programs\AutomationTool\AutomationUtils\ProjectParams.cs:line 1072
UATHelper: Packaging (Windows (64-bit)):           at BuildCookRun.SetupParams() in D:\Build\++UE4+Licensee\Sync\Engine\Saved\CsTools\Engine\Source\Programs\AutomationTool\Scripts\BuildCookRun.Automation.cs:line 46
UATHelper: Packaging (Windows (64-bit)):           at BuildCookRun.ExecuteBuild() in D:\Build\++UE4+Licensee\Sync\Engine\Saved\CsTools\Engine\Source\Programs\AutomationTool\Scripts\BuildCookRun.Automation.cs:line 37
UATHelper: Packaging (Windows (64-bit)):           at AutomationTool.BuildCommand.Execute() in D:\Build\++UE4+Licensee\Sync\Engine\Saved\CsTools\Engine\Source\Programs\AutomationTool\AutomationUtils\BuildCommand.cs:line 263
UATHelper: Packaging (Windows (64-bit)):           at AutomationTool.Automation.Execute(List`1 CommandsToExecute, Dictionary`2 Commands) in D:\Build\++UE4+Licensee\Sync\Engine\Saved\CsTools\Engine\Source\Programs\AutomationTool\AutomationUtils\Automation.cs:line 539
UATHelper: Packaging (Windows (64-bit)):           at AutomationTool.Automation.Process(String[] Arguments, StartupTraceListener StartupListener) in D:\Build\++UE4+Licensee\Sync\Engine\Saved\CsTools\Engine\Source\Programs\AutomationTool\AutomationUtils\Automation.cs:line 509
UATHelper: Packaging (Windows (64-bit)):           at AutomationTool.Program.MainProc(String[] Arguments, StartupTraceListener StartupListener) in D:\Build\++UE4+Licensee\Sync\Engine\Saved\CsTools\Engine\Source\Programs\AutomationTool\Program.cs:line 176
UATHelper: Packaging (Windows (64-bit)):           at AutomationTool.Program.<>c__DisplayClass1_0.<Main>b__2() in D:\Build\++UE4+Licensee\Sync\Engine\Saved\CsTools\Engine\Source\Programs\AutomationTool\Program.cs:line 88
UATHelper: Packaging (Windows (64-bit)):           at AutomationTool.InternalUtils.RunSingleInstance(Func`1 Main) in D:\Build\++UE4+Licensee\Sync\Engine\Saved\CsTools\Engine\Source\Programs\AutomationTool\AutomationUtils\Utils.cs:line 731
UATHelper: Packaging (Windows (64-bit)):           at AutomationTool.Program.Main(String[] Arguments) in D:\Build\++UE4+Licensee\Sync\Engine\Saved\CsTools\Engine\Source\Programs\AutomationTool\Program.cs:line 88
UATHelper: Packaging (Windows (64-bit)):        (see C:\Users\Chozabu\AppData\Roaming\Unreal Engine\AutomationTool\Logs\e+Epic+Games+UE_4.25\Log.txt for full exception trace)
UATHelper: Packaging (Windows (64-bit)): AutomationTool exiting with ExitCode=1 (Error_Unknown)
PackagingResults: Error: System.ArgumentException: An item with the same key has already been added.
`

Not sure on exact cause, but removing either this plugin or advanced sessions seems to fix the issue

**Comment by SRombauts** [comment]
Is it happening with the git plugin alone ?

**Comment by SRombauts** [comment]
might be because this git plugin v2 uses the same name as the v1 one in Engine

**Comment by chozabu** [comment]
It does not happen with the gitv2 plugin alone (or with the advancedsessions plugin alone)
